### ISSUE TITLE
Updating to CUDA 9.1 from CUDA 8.0

### ISSUE THREAD

**Issue by chamilka** [deeplearning4j/nd4j#2852]
#### Issue Description

I have a program running deeplearning neural network on CUDA 8.0 successfully. I tried to update it to CUDA 9.1 by updating the pom file.

```
<nd4j.backend>nd4j-cuda-9.1-platform</nd4j.backend>

<nd4j.version>1.0.0-alpha</nd4j.version>
<dl4j.version>1.0.0-alpha</dl4j.version>
<datavec.version>1.0.0-alpha</datavec.version>
<arbiter.version>1.0.0-alpha</arbiter.version>
<rl4j.version>1.0.0-alpha</rl4j.version>

```
First I tried one of your examples (latest versions) and got the following error.

> o.n.l.f.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: C:\Users\ASUS\.javacpp\cache\cuda-9.1-7.1-1.4.1-windows-x86_64.jar\org\bytedeco\javacpp\windows-x86_64\jnicuda.dll: The specified procedure could not be found
> o.n.l.f.Nd4jBackend - Skipped [JCublasBackend] backend (unavailable): java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cuda
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.deeplearning4j.examples.multigpu.vgg16.MultiGpuLenetMnistExample.main(MultiGpuLenetMnistExample.java:39)
> Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6230)
> 	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
> 	... 1 more
> Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:259)
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6227)
> 	... 2 more

At that point since I had both cuda 8.0 and cuda 9.1 installed I uninstalled everything and installed cuda 9.1
I'm running this on windows 10.

Now nd4j Initialization has no problem. BUT I get the following error when try to train the network.

> Exception in thread "Thread-0" org.nd4j.linalg.exception.ND4JException: CUDA exception happened. Terminating. Last op: [null]
> 	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.register(cudaEvent_t.java:63)
> 	at org.nd4j.jita.flow.impl.SynchronousFlowController.registerAction(SynchronousFlowController.java:250)
> 	at org.nd4j.jita.handler.impl.CudaZeroHandler.registerAction(CudaZeroHandler.java:1269)
> 	at org.nd4j.jita.allocator.impl.AtomicAllocator.registerAction(AtomicAllocator.java:1017)
> 	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:696)
> 	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5853)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:338)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:297)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:264)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:211)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:367)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:458)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)
> 	at com.axiohelix.oist.deeplearninggpu.ClassificationManager.runClassification(ClassificationManager.java:201)
> 	at com.axiohelix.oist.deeplearninggpu.Starter.run(Starter.java:63)
> 	at java.lang.Thread.run(Thread.java:748)
> CUDA error at D:/jenkins/workspace/libnd4j_latest_release_windows-x86_64-cuda-9.1/libnd4j/blas/cuda/NativeOps.cu:4849 code=4(cudaErrorLaunchFailure) "cudaStreamSynchronize(*stream)" 
> CUDA error at D:/jenkins/workspace/libnd4j_latest_release_windows-x86_64-cuda-9.1/libnd4j/blas/cuda/NativeOps.cu:4541 code=4(cudaErrorLaunchFailure) "result"

It says something about "D:/jenkins/workspace/" which I'm confused about.

Thank you

**Comment by raver119** [comment]
Please set environment variable ND4J_DEBUG to `true`, run your app once again, and show me your output.

**Comment by chamilka** [comment]
I get the following error after setting ND4J_DEBUG to true

> Exception in thread "Thread-0" java.lang.NullPointerException
> 	at org.nd4j.jita.allocator.pointers.CudaPointer.<init>(CudaPointer.java:22)
> 	at org.nd4j.jita.allocator.pointers.cuda.cudaEvent_t.<init>(cudaEvent_t.java:33)
> 	at org.nd4j.jita.concurrency.EventsProvider.getEvent(EventsProvider.java:34)
> 	at org.nd4j.jita.flow.impl.SynchronousFlowController.registerAction(SynchronousFlowController.java:249)
> 	at org.nd4j.jita.handler.impl.CudaZeroHandler.registerAction(CudaZeroHandler.java:1269)
> 	at org.nd4j.jita.allocator.impl.AtomicAllocator.registerAction(AtomicAllocator.java:1017)
> 	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.concat(JCublasNDArrayFactory.java:696)
> 	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:5853)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertWritablesBatched(RecordReaderMultiDataSetIterator.java:338)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.convertFeaturesOrLabels(RecordReaderMultiDataSetIterator.java:297)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.nextMultiDataSet(RecordReaderMultiDataSetIterator.java:264)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderMultiDataSetIterator.next(RecordReaderMultiDataSetIterator.java:211)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:367)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:458)
> 	at org.deeplearning4j.datasets.datavec.RecordReaderDataSetIterator.next(RecordReaderDataSetIterator.java:85)
> 	at com.axiohelix.oist.deeplearninggpu.ClassificationManager.runClassification(ClassificationManager.java:201)
> 	at com.axiohelix.oist.deeplearninggpu.Starter.run(Starter.java:63)
> 	at java.lang.Thread.run(Thread.java:748)
> CUDA error at D:/jenkins/workspace/libnd4j_latest_release_windows-x86_64-cuda-9.1/libnd4j/blas/cuda/NativeOps.cu:4849 code=4(cudaErrorLaunchFailure) "cudaStreamSynchronize(*stream)" 
> CUDA error at D:/jenkins/workspace/libnd4j_latest_release_windows-x86_64-cuda-9.1/libnd4j/blas/cuda/NativeOps.cu:4530 code=4(cudaErrorLaunchFailure) "result" 
> 
>

**Comment by raver119** [comment]
No, please post full output. Log you're posting isn't relevant, because it shows what happens after crash.

**Comment by raver119** [comment]
Also, please use https://gist.github.com

**Comment by raver119** [comment]
Also, please tell me, what's your GPU model name?

**Comment by chamilka** [comment]
GPU Model : GeForce GTX 1050
I'm using Eclipse to run this program (same I did for CUDA 8.0) So I get only this in the console. Some of the message are from my program.

https://gist.github.com/chamilka/cb1167bdf38f09a1f5b530159b79afd7

I have following in logback.xml

https://gist.github.com/chamilka/c85ccfb2b84c4b0e2c28ec3f11754232

What am I missing?

**Comment by chamilka** [comment]
Here is my source code

https://gist.github.com/chamilka/50b30ac8c03a0e3dd1749518556dccf2

Before I set ND4J_DEBUG I got the error.
https://gist.github.com/chamilka/d9a210ec4cd5ca7b69a9e5c9bd197f09

After setting ND4J_DEBUG=true I got the error
https://gist.github.com/chamilka/7e7d2d17d414b06cab5376e3f1270fb7

So ND4J_DEBUG has done something for sure but I'm not sure if that is the output it should generate.

**Comment by chamilka** [comment]
Yes I think it is the latest version (391.35)

![gpu](https://user-images.githubusercontent.com/12293116/39165676-42fb0088-47a3-11e8-998e-af3ecf07dcdd.png)

**Comment by samuelchapas** [comment]
Have a nice day contributors to DeepLearning4j:
Let me congratulate you for your amazing job, actually  I am working with some examples of DeepLearning4j, but I got this problem after installing and working on dependencies.
Previously I have downloaded the Backend dependency and set up the enviroments, this is the Log from the console after running it.

```
`14:13:13,976` WARN  ~ Skipped [JCublasBackend] backend (unavailable): java.lang.UnsatisfiedLinkError: .../.javacpp/cache/cuda-8.0-6.0-1.3-linux-x86_64.jar/org/bytedeco/javacpp/linux-x86_64/libjnicuda.so: libcuda.so.1: cannot open shared object file: No such file or directory
14:13:14,659 WARN  ~ Skipped [JCublasBackend] backend (unavailable): java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cuda
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.run(EncoderDecoderLSTM.java:213)
	at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.main(EncoderDecoderLSTM.java:209)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6089)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 2 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:258)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6086)
	... 3 more
```
This is the link for the project:
[https://github.com/samuelchapas/SentencePrediction]
I will be thankfull for any help in order to solve this issue

**Comment by raver119** [comment]
@samuelchapas  Your problem has nothing to do with original issue, please create your own. And don't mix different versions of framework in one pom.xml. That's probably the problem in your case.

**Comment by samuelchapas** [comment]
ok, already solved it thanks, I changed to CUDA to Native BACKEnd

**Comment by ishumaurya11321** [comment]
i also want to  run my programme on GPU so my question is do i need to install GPU toolkit first ?
2 question is do i need to write <nd4j.backend>nd4j-cuda-9.1-platform</nd4j.backend> in pom after instlling toolkit
My programme still running on cpu so help me
